### ISSUE TITLE
Use huggingface to load LED model？

### ISSUE THREAD

**Issue by BinchaoPeng** [allenai/ms2#2]
Hi，I use huggingface env to load LED model for getting embeding vector， but the error shows that dim size is fault about [16389,768] and [1072, 768].

However, I have Seen, in this repo, you used LED model and import transformers, So could you tell me what I should pay attention to and how to make it work.

if you see, please reply me soon,Thanks!

**Comment by jayded** [comment]
Thank you for the question! I've updated my notifications for this repo so I'll receive updates.

This repo is implemented with an old version of the huggingface transformers library, a prerelease of the longformer library from before the official release, and a forked pytorch lightning version with some fixes. It *might* work anyway, but that's definitely not a use case I can help with.

If you want to attempt to use a newer huggingface transformers, you will need to use one of the models specified in [the set up instructions](https://github.com/allenai/ms2#set-up): [16k tokens bart-base](https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/longformer-encdec-base-16384.tar.gz), or [16k tokens bart-large](https://ai2-s2-research.s3-us-west-2.amazonaws.com/longformer/longformer-encdec-large-16384.tar.gz).

In either case, I **strongly** recommend following [the set up instructions](https://github.com/allenai/ms2#set-up) instructions as this repo depends on a [fixed and modified pytorch lightning](https://github.com/ibeltagy/pytorch-lightning/tree/v0.8.5_fixes), a [fixed version of transformers for longformer with gradient checkpoint support (approximate commit)](https://github.com/ibeltagy/transformers/commit/52d6236dc15ad5142b4146ff74d2ec973fa3da22), and a [specific longformer checkpoint](https://github.com/allenai/longformer/commit/55c1f5f75d6f33b7ee23af0caf0392a52f8d4f4c). Getting this working from the release will be a good first step for anything you wish to do with the repo.

At the moment I have no plans to update these for newer releases.

**Comment by jayded** [comment]
We have released trained models in [The ReadMe](https://github.com/allenai/ms2/blob/master/README.md).

This issue has been stale for awhile, so I'm closing, please open another one if those don't work for you.

**Comment by JohnGiorgi** [comment]
A HuggingFace version is available here: https://huggingface.co/allenai/led-base-16384-ms2

**Comment by BinchaoPeng** [comment]
Thanks!
