### ISSUE TITLE
Accessible in HF Datasets?

### ISSUE THREAD

**Issue by CShorten** [allenai/ms2#3]
This dataset looks awesome! Will this be available in the HuggingFace Dataset library soon?

**Comment by jayded** [comment]
Thank you for the question! I've updated my notifications for this repo so I'll receive updates.

@lucylw addressed this in https://github.com/allenai/ms2/pull/4 - we release this under a license that's different from Huggingface datasets. License compatibility is a question above my paygrade.

**Comment by JohnGiorgi** [comment]
Available in HF datasets here: https://huggingface.co/datasets/allenai/mslr2022
